"""
Django settings for ttscanner_backend project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
from dotenv import load_dotenv, dotenv_values
import os

import pymysql
pymysql.install_as_MySQLdb()

BASE_DIR = Path(__file__).resolve().parent.parent

# Reload the .env file completely
env_path = BASE_DIR / ".env"
env_config = dotenv_values(env_path) 
for k, v in env_config.items():
    os.environ[k] = v  

load_dotenv(dotenv_path=env_path, override=True) 

ENVIRONMENT = os.getenv("ENVIRONMENT", "development")

# To this (includes your PipeOps domains):
ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS", 
    "localhost,127.0.0.1,marine-ship.igris.cloud,ment-direction.pipeops.app"
).split(",")

# SECURITY
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-(nf+o%mj0u60j=7jb9t@f%p3vbe6mq+n_$h7e#p&)fol+3kzc^"
)

DEBUG = True 

# ADD THESE LINES RIGHT HERE:
CSRF_TRUSTED_ORIGINS = [
    'https://ment-direction.pipeops.app',
    'https://*.pipeops.app',
]

# Also add if you're using HTTPS:
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Application definition
INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'silk',
    'ttscanner',
    'corsheaders',
]

# # Tell Django to use your custom user model
# AUTH_USER_MODEL = 'ttscanner.MENTUser'

# Also add authentication backend
# AUTHENTICATION_BACKENDS = [
#     'django.contrib.auth.backends.ModelBackend',
# ]
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'silk.middleware.SilkyMiddleware', 
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Silk configuration (SAFE for production)
SILKY_AUTHENTICATION = True  # Requires login
SILKY_AUTHORISATION = True   # Only for authorized users
SILKY_PERMISSIONS = lambda user: user.is_superuser  # Only superusers
SILKY_INTERCEPT_PERCENT = 100  # Profile 100% of requests
SILKY_MAX_RECORDED_REQUESTS = 10**4  # Store up to 10k requests
SILKY_MAX_RECORDED_REQUESTS_CHECK_PERCENT = 10

ROOT_URLCONF = 'ttscanner_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ttscanner_backend.wsgi.application'

# Database
db_host = os.getenv('DB_HOST', '')
db_port = os.getenv('DB_PORT', '')

# If DB_HOST contains port (e.g., "marine-ship.igris.cloud:17143")
if ':' in db_host:
    host, port_from_host = db_host.split(':')
    # Use port from DB_HOST if it exists
    port = port_from_host
else:
    host = db_host
    port = db_port if db_port else '3306'


# Database - USE THE PARSED VALUES!
DATABASES = {
    "default": {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': host,  
        'PORT': port,  
        'OPTIONS': {
            'charset': 'utf8mb4',
            'connect_timeout': 10,  
        },
        'CONN_MAX_AGE': 300, 
    }
}

# Add debug logging to see what values are being used
print(f"DEBUG: Database connection - HOST: {host}, PORT: {port}, NAME: {os.getenv('DB_NAME')}")


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DATA_UPLOAD_MAX_NUMBER_FIELDS = 5000

# DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}

# Celery (Local Redis)
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/0")

CELERY_TIMEZONE = "UTC"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 300
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

# Email
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 2525))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "False") == "True"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False") == "True"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# SMS (Twilio)
TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_API_KEY_SID = os.getenv("TWILIO_API_KEY_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_PHONE_NUMBER = os.getenv("TWILIO_PHONE_NUMBER")

# CORS
CORS_ALLOW_ALL_ORIGINS = False
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "http://localhost:5173")
CORS_ALLOWED_ORIGINS = [
    os.getenv("FRONTEND_BASE_URL", "http://localhost:5173"),
]

