# Generated by Django 5.2.8 on 2025-11-13 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algo_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'algos',
            },
        ),
        migrations.CreateModel(
            name='CSVSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('schema_json', models.JSONField(default=dict)),
                ('global_alert_fields', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'csv_schemas',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_name', models.CharField(max_length=255, unique=True)),
                ('interval_minutes', models.PositiveIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'intervals',
            },
        ),
        migrations.CreateModel(
            name='FileAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(editable=False, max_length=255, unique=True)),
                ('file_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('algo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttscanner.algo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttscanner.group')),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttscanner.interval')),
            ],
            options={
                'db_table': 'file_associations',
                'unique_together': {('algo', 'group', 'interval')},
            },
        ),
        migrations.CreateModel(
            name='CustomAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('condition_type', models.CharField(choices=[('change', 'Any Change'), ('increase', 'Increased'), ('decrease', 'Decreased'), ('equals', 'Equals Specific Value'), ('threshold_cross', 'Crossed Threshold')], max_length=50)),
                ('compare_value', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file_association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttscanner.fileassociation')),
            ],
            options={
                'db_table': 'custom_alerts',
            },
        ),
        migrations.CreateModel(
            name='GlobalAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text')], max_length=50)),
                ('condition_type', models.CharField(choices=[('change', 'Any Change'), ('increase', 'Increased'), ('decrease', 'Decreased'), ('equals', 'Equals Specific Value'), ('threshold_cross', 'Crossed Threshold')], max_length=50)),
                ('compare_value', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ttscanner.csvschema')),
            ],
            options={
                'db_table': 'global_alert_rules',
            },
        ),
        migrations.CreateModel(
            name='MainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_json', models.JSONField(default={})),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('file_association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttscanner.fileassociation')),
                ('schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ttscanner.csvschema')),
            ],
            options={
                'db_table': 'main_data',
            },
        ),
    ]
