# Generated by Django 5.2.8 on 2025-11-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0002_fileassociation_last_fetched_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_tt_admin',
            field=models.BooleanField(default=True),
        ),
    ]
