# Generated by Django 5.2.8 on 2025-11-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0003_alter_userprofile_is_tt_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_tt_admin',
            field=models.BooleanField(default=False),
        ),
    ]
