# Generated by Django 5.2.8 on 2025-11-14 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0004_alter_userprofile_is_tt_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileassociation',
            name='csv_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ttscanner.csvschema'),
        ),
    ]
