# Generated by Django 5.2.8 on 2025-11-14 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0005_fileassociation_csv_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maindata',
            name='schema',
        ),
        migrations.RemoveField(
            model_name='fileassociation',
            name='csv_schema',
        ),
        migrations.RemoveField(
            model_name='globalalertrule',
            name='schema',
        ),
        migrations.DeleteModel(
            name='CSVSchema',
        ),
    ]
