# Generated by Django 5.2.8 on 2025-11-16 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0006_remove_maindata_schema_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MENTUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.IntegerField(unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('regular', 'Regular')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttscanner.mentuser'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
