# Generated by Django 5.2.8 on 2025-11-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0007_mentuser_alter_customalert_user_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='interval_name',
            field=models.CharField(choices=[('1min', '1min'), ('5min', '5min'), ('15min', '15min'), ('30min', '30min'), ('60min', '60min'), ('daily', 'daily')], max_length=10, unique=True),
        ),
    ]
