# Generated by Django 5.2.8 on 2025-11-16 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0008_alter_interval_interval_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileassociation',
            name='headers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalalertrule',
            name='file_association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ttscanner.fileassociation'),
        ),
        migrations.AlterField(
            model_name='customalert',
            name='file_association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ttscanner.fileassociation'),
        ),
    ]
