# Generated by Django 5.2.8 on 2025-11-16 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0009_fileassociation_headers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customalert',
            name='file_association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttscanner.fileassociation'),
        ),
        migrations.AlterField(
            model_name='globalalertrule',
            name='file_association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttscanner.fileassociation'),
        ),
    ]
