# Generated by Django 5.2.8 on 2025-11-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0010_alter_customalert_file_association_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='interval_name',
            field=models.CharField(choices=[('1min', '1min'), ('2min', '2min'), ('5min', '5min'), ('15min', '15min'), ('30min', '30min'), ('60min', '60min'), ('daily', 'daily')], max_length=10, unique=True),
        ),
    ]
