# Generated by Django 5.2.8 on 2025-11-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0011_alter_interval_interval_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
