# Generated by Django 5.2.8 on 2025-11-17 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0012_alter_group_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileassociation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ttscanner.group'),
        ),
    ]
