# Generated by Django 5.2.8 on 2025-11-17 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0013_alter_fileassociation_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='TriggeredAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('custom_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ttscanner.customalert')),
                ('file_association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttscanner.fileassociation')),
                ('global_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ttscanner.globalalertrule')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
