# Generated by Django 5.2.8 on 2025-11-19 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0015_alter_interval_interval_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triggeredalert',
            name='details',
        ),
        migrations.AddField(
            model_name='triggeredalert',
            name='last_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalalertrule',
            name='file_association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_alerts', to='ttscanner.fileassociation'),
        ),
    ]
