# Generated by Django 5.2.8 on 2025-11-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0016_remove_triggeredalert_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triggeredalert',
            name='last_value',
        ),
        migrations.AddField(
            model_name='globalalertrule',
            name='last_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
