# Generated by Django 5.2.8 on 2025-11-20 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0017_remove_triggeredalert_last_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindata',
            name='file_association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maindata', to='ttscanner.fileassociation'),
        ),
    ]
