# Generated by Django 5.2.8 on 2025-11-21 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0018_alter_maindata_file_association'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttscanner.fileassociation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttscanner.mentuser')),
            ],
            options={
                'unique_together': {('user', 'file_association')},
            },
        ),
    ]
