# Generated by Django 5.2.8 on 2025-11-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0019_favoriterow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriterow',
            unique_together={('user', 'file_association')},
        ),
        migrations.AddField(
            model_name='favoriterow',
            name='row_hash',
            field=models.CharField(default='temp_hash', editable=False, max_length=64),
        ),
    ]
