# Generated by Django 5.2.8 on 2025-11-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0020_alter_favoriterow_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customalert',
            name='field_type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text')], default='numeric', max_length=50),
        ),
    ]
