# Generated by Django 5.2.8 on 2025-11-21 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0021_customalert_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customalert',
            name='file_association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_alerts', to='ttscanner.fileassociation'),
        ),
    ]
