# Generated by Django 5.2.8 on 2025-11-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0022_alter_customalert_file_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='customalert',
            name='last_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
