# Generated by Django 5.2.8 on 2025-11-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0023_customalert_last_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customalert',
            name='last_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='globalalertrule',
            name='last_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
