# Generated by Django 5.2.8 on 2025-11-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0025_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='delivery_method',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='delivery_methods',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
