# Generated by Django 5.2.8 on 2025-11-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0026_remove_usersettings_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalalertrule',
            name='symbol_interval',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
