# Generated by Django 5.2.8 on 2025-11-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0027_globalalertrule_symbol_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='customalert',
            name='symbol_interval',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customalert',
            name='field_type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text')], max_length=50),
        ),
    ]
