# Generated by Django 5.2.8 on 2025-11-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0028_customalert_symbol_interval_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriterow',
            unique_together={('user', 'file_association', 'row_hash')},
        ),
    ]
