# Generated by Django 5.2.8 on 2025-11-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0029_alter_favoriterow_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterow',
            name='row_hash',
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
