# Generated by Django 5.2.8 on 2025-11-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0030_alter_favoriterow_row_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
