# Generated by Django 5.2.8 on 2025-11-30 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0031_alter_group_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileassociation',
            name='algo_name_copy',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fileassociation',
            name='group_name_copy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fileassociation',
            name='interval_name_copy',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fileassociation',
            name='algo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ttscanner.algo'),
        ),
        migrations.AlterField(
            model_name='fileassociation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ttscanner.group'),
        ),
        migrations.AlterField(
            model_name='fileassociation',
            name='interval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ttscanner.interval'),
        ),
    ]
