# Generated by Django 5.2.8 on 2025-12-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0032_fileassociation_algo_name_copy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='interval_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
