# Generated by Django 5.2.8 on 2025-12-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0033_alter_interval_interval_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalalertrule',
            name='field_type',
        ),
        migrations.AlterField(
            model_name='globalalertrule',
            name='compare_value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='globalalertrule',
            name='symbol_interval',
            field=models.CharField(max_length=50),
        ),
    ]
