# Generated by Django 5.2.8 on 2025-12-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0034_remove_globalalertrule_field_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileassociation',
            name='target_1_hit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileassociation',
            name='target_2_hit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
