# Generated by Django 5.2.8 on 2025-12-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0035_fileassociation_target_1_hit_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileassociation',
            name='target_1_hit_at',
        ),
        migrations.RemoveField(
            model_name='fileassociation',
            name='target_2_hit_at',
        ),
        migrations.AddField(
            model_name='customalert',
            name='target_1_hit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customalert',
            name='target_2_hit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalalertrule',
            name='target_1_hit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalalertrule',
            name='target_2_hit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
