# Generated by Django 5.2.8 on 2025-12-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0036_remove_fileassociation_target_1_hit_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalalertrule',
            name='compare_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
