# Generated by Django 5.2.8 on 2025-12-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0037_alter_globalalertrule_compare_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='algo',
            name='price_field_key',
            field=models.CharField(default='last price', max_length=100),
        ),
        migrations.AddField(
            model_name='algo',
            name='supports_direction',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='algo',
            name='supports_targets',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='algo',
            name='supports_volume_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
