# Generated by Django 5.2.8 on 2025-12-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0039_auto_20251206_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileassociation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('unknown', 'Unknown Algo')], default='active', max_length=50),
        ),
    ]
