# Generated by Django 5.2.8 on 2025-12-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0040_fileassociation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggeredalert',
            name='message',
            field=models.TextField(default='No message'),
            preserve_default=False,
        ),
    ]
