# Generated by Django 5.2.8 on 2025-12-07 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0041_triggeredalert_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('last_row_data', models.JSONField(default=dict)),
                ('last_price', models.FloatField(blank=True, null=True)),
                ('last_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('target1_hit', models.BooleanField(default=False)),
                ('target2_hit', models.BooleanField(default=False)),
                ('last_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('last_alerts', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_states', to='ttscanner.fileassociation')),
            ],
            options={
                'db_table': 'symbol_states',
                'unique_together': {('file_association', 'symbol')},
            },
        ),
    ]
