# Generated by Django 5.2.8 on 2025-12-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0042_symbolstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileassociation',
            name='data_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
