# Generated by Django 5.2.8 on 2026-01-07 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0046_add_symbol_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('Email & SMS', 'Email & SMS')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customalert',
            name='field_type',
        ),
        migrations.AlterUniqueTogether(
            name='favoriterow',
            unique_together={('user', 'row_id', 'file_association')},
        ),
        migrations.AddField(
            model_name='favoriterow',
            name='row_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='mentuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='mentuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='triggeredalert',
            name='alert_source',
            field=models.CharField(choices=[('system', 'System'), ('global', 'Global'), ('custom', 'Custom')], default='manual', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favoriterow',
            name='row_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='favoriterow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='ttscanner.mentuser'),
        ),
        migrations.AlterModelTable(
            name='maindata',
            table=None,
        ),
        migrations.RemoveField(
            model_name='favoriterow',
            name='row_data',
        ),
    ]
