# Generated by Django 5.2.8 on 2026-01-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0047_announcement_remove_customalert_field_type_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='announcement',
            table='announcements',
        ),
        migrations.AlterModelTable(
            name='favoriterow',
            table='ttscanner_favoriterow',
        ),
        migrations.AlterModelTable(
            name='maindata',
            table='main_data',
        ),
        migrations.AlterModelTable(
            name='mentuser',
            table='ttscanner_mentuser',
        ),
        migrations.AlterModelTable(
            name='triggeredalert',
            table='triggered_alerts',
        ),
        migrations.AlterModelTable(
            name='usersettings',
            table='ttscanner_usersettings',
        ),
    ]
