# Generated by Django 5.2.8 on 2026-01-08 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0048_alter_announcement_table_alter_favoriterow_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favoriterow',
            table='favoriterow',
        ),
        migrations.AlterModelTable(
            name='mentuser',
            table='mentuser',
        ),
        migrations.AlterModelTable(
            name='usersettings',
            table='usersettings',
        ),
    ]
