# Generated by Django 5.2.8 on 2026-01-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0049_alter_favoriterow_table_alter_mentuser_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='announcement',
            table='ttscanner_announcement',
        ),
        migrations.AlterModelTable(
            name='favoriterow',
            table='ttscanner_favoriterow',
        ),
        migrations.AlterModelTable(
            name='mentuser',
            table='ttscanner_mentuser',
        ),
        migrations.AlterModelTable(
            name='triggeredalert',
            table='ttscanner_triggeredalert',
        ),
        migrations.AlterModelTable(
            name='usersettings',
            table='ttscanner_usersettings',
        ),
    ]
