# Generated by Django 5.2.8 on 2026-01-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0050_alter_announcement_table_alter_favoriterow_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algo',
            name='algo_name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='algo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='algo',
            name='supports_targets',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('Email & SMS', 'Email & SMS')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customalert',
            name='condition_type',
            field=models.CharField(choices=[('change', 'Any Change'), ('increase', 'Increased'), ('decrease', 'Decreased'), ('equals', 'Equals Specific Value'), ('threshold_cross', 'Crossed Threshold')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='customalert',
            name='field_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customalert',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='customalert',
            name='symbol_interval',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='favoriterow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='favoriterow',
            name='row_id',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='fileassociation',
            name='algo_name_copy',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fileassociation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='fileassociation',
            name='file_name',
            field=models.CharField(db_index=True, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='fileassociation',
            name='group_name_copy',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fileassociation',
            name='interval_name_copy',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fileassociation',
            name='last_fetched_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileassociation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('unknown', 'Unknown Algo')], db_index=True, default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='globalalertrule',
            name='condition_type',
            field=models.CharField(choices=[('change', 'Any Change'), ('increase', 'Increased'), ('decrease', 'Decreased'), ('equals', 'Equals Specific Value'), ('threshold_cross', 'Crossed Threshold')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='globalalertrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='globalalertrule',
            name='field_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='globalalertrule',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='globalalertrule',
            name='symbol_interval',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='interval',
            name='interval_minutes',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='interval',
            name='interval_name',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='maindata',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='mentuser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mentuser',
            name='external_user_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mentuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('regular', 'Regular')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='mentuser',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='symbolstate',
            name='last_direction',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='symbolstate',
            name='last_price',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='symbolstate',
            name='symbol',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='symbolstate',
            name='target1_hit',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='symbolstate',
            name='target2_hit',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='symbolstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='triggeredalert',
            name='acknowledged',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='triggeredalert',
            name='alert_source',
            field=models.CharField(choices=[('system', 'System'), ('global', 'Global'), ('custom', 'Custom')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='triggeredalert',
            name='symbol',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='triggeredalert',
            name='triggered_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='alert_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='alerts_enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='algo',
            index=models.Index(fields=['-created_at'], name='algos_created_042eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['-created_at'], name='ttscanner_a_created_5b38bf_idx'),
        ),
        migrations.AddIndex(
            model_name='customalert',
            index=models.Index(fields=['user', 'is_active', '-created_at'], name='custom_aler_user_id_c39a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='customalert',
            index=models.Index(fields=['file_association', 'user', 'is_active'], name='custom_aler_file_as_6ddbae_idx'),
        ),
        migrations.AddIndex(
            model_name='customalert',
            index=models.Index(fields=['symbol_interval', 'field_name', 'user'], name='custom_aler_symbol__50fff7_idx'),
        ),
        migrations.AddIndex(
            model_name='favoriterow',
            index=models.Index(fields=['user', '-created_at'], name='ttscanner_f_user_id_37977d_idx'),
        ),
        migrations.AddIndex(
            model_name='favoriterow',
            index=models.Index(fields=['file_association', 'user'], name='ttscanner_f_file_as_c78e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='fileassociation',
            index=models.Index(fields=['-created_at'], name='file_associ_created_fd9d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='fileassociation',
            index=models.Index(fields=['status', 'created_at'], name='file_associ_status_eef1f9_idx'),
        ),
        migrations.AddIndex(
            model_name='fileassociation',
            index=models.Index(fields=['algo', 'interval'], name='file_associ_algo_id_68b0b5_idx'),
        ),
        migrations.AddIndex(
            model_name='fileassociation',
            index=models.Index(fields=['file_name', 'status'], name='file_associ_file_na_cee892_idx'),
        ),
        migrations.AddIndex(
            model_name='globalalertrule',
            index=models.Index(fields=['file_association', 'is_active', '-created_at'], name='global_aler_file_as_ee5171_idx'),
        ),
        migrations.AddIndex(
            model_name='globalalertrule',
            index=models.Index(fields=['symbol_interval', 'field_name'], name='global_aler_symbol__a4c543_idx'),
        ),
        migrations.AddIndex(
            model_name='globalalertrule',
            index=models.Index(fields=['is_active', '-created_at'], name='global_aler_is_acti_835400_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['-created_at'], name='groups_created_033f65_idx'),
        ),
        migrations.AddIndex(
            model_name='maindata',
            index=models.Index(fields=['file_association', '-last_updated'], name='main_data_file_as_e0440a_idx'),
        ),
        migrations.AddIndex(
            model_name='symbolstate',
            index=models.Index(fields=['file_association', '-updated_at'], name='symbol_stat_file_as_2657b3_idx'),
        ),
        migrations.AddIndex(
            model_name='symbolstate',
            index=models.Index(fields=['symbol', 'file_association'], name='symbol_stat_symbol_5f65fa_idx'),
        ),
        migrations.AddIndex(
            model_name='symbolstate',
            index=models.Index(fields=['last_price'], name='symbol_stat_last_pr_7dbf4c_idx'),
        ),
        migrations.AddIndex(
            model_name='triggeredalert',
            index=models.Index(fields=['-triggered_at', 'acknowledged'], name='ttscanner_t_trigger_7574ed_idx'),
        ),
        migrations.AddIndex(
            model_name='triggeredalert',
            index=models.Index(fields=['file_association', '-triggered_at'], name='ttscanner_t_file_as_fa503f_idx'),
        ),
        migrations.AddIndex(
            model_name='triggeredalert',
            index=models.Index(fields=['acknowledged', 'triggered_at'], name='ttscanner_t_acknowl_58858e_idx'),
        ),
    ]
