# Generated by Django 5.2.8 on 2026-01-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0051_alter_algo_algo_name_alter_algo_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='color_mappings',
            field=models.JSONField(blank=True, default=dict, help_text='User-selected colors for color-blind theme'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('color-blind', 'Color Blind')], default='dark', max_length=15),
        ),
    ]
