# Generated by Django 5.2.8 on 2026-01-21 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0052_usersettings_color_mappings_alter_usersettings_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileColorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=7)),
                ('meaning', models.CharField(max_length=255)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_mappings', to='ttscanner.fileassociation')),
            ],
            options={
                'unique_together': {('file', 'color_code')},
            },
        ),
    ]
