# Generated by Django 5.2.8 on 2026-01-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0053_filecolormapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='color_mappings',
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=10),
        ),
        migrations.DeleteModel(
            name='FileColorMapping',
        ),
    ]
