# Generated by Django 5.2.8 on 2026-01-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0054_remove_usersettings_color_mappings_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maindata',
            unique_together={('file_association',)},
        ),
    ]
