# Generated by Django 5.2.8 on 2026-01-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttscanner', '0055_alter_maindata_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggeredalert',
            name='sent_to_ui',
            field=models.BooleanField(default=False),
        ),
    ]
