from django.urls import path
from .views import (
    FileAssociationCreateView, CSVUploadView, 
    FileAssociationUpdateView, FileAssociationDeleteView,
    FileAssociationListView, GlobalAlertCreateView, 
    GlobalAlertUpdateView, GlobalAlertDeleteView, 
    GlobalAlertListView, AlgoListView,
    GroupListView, GroupCreateView,
    GroupUpdateView, GroupDeleteView,
    IntervalListView, IntervalCreateView,
    IntervalUpdateView, IntervalDeleteView,
    AlgoCreateView, AlgoUpdateView, 
    AlgoDeleteView, SymIntListView,
    UserRoleView, send_announcement
)
from .regular_user_views import(
    CSVListView, FilterCSVView,
    CSVHeaderView, SortCSVView,
    FavoriteRowView, CustomAlertCreateView,
    CustomAlertUpdateView, CustomAlertDeleteView,
    UserSettingsCreateView, UpdateUserSettingsView,
    UserSettingsView, AlgoGroupsView, 
    AlgoGroupIntervalsView, FileAssociationLookupView, 
    FavoriteRowListView, DeleteFavoriteView,
    CustomAlertView, UserTriggeredAlertsView
)
from ttscanner import regular_user_views

urlpatterns = [
    path('algos/', AlgoListView.as_view(), name='algo-list'),
    path('algos/create/', AlgoCreateView.as_view(), name='algo-create'),
    path('algos/update/<int:pk>/', AlgoUpdateView.as_view(), name='algo-update'),
    path('algos/delete/<int:pk>/', AlgoDeleteView.as_view(), name='algo-delete'),
    path("algos/<int:algo_pk>/groups/", AlgoGroupsView.as_view(), name="algo-groups"),
    path("algos/<int:algo_pk>/groups/<group_pk>/intervals/", AlgoGroupIntervalsView.as_view(), name="algo-group-intervals"),
    path("file-association/lookup/", FileAssociationLookupView.as_view(), name="file-association-lookup"),
    path('groups/', GroupListView.as_view(), name='group-list'),
    path('groups/create/', GroupCreateView.as_view(), name='group-create'),
    path('groups/update/<int:pk>/', GroupUpdateView.as_view(), name='group-update'),
    path('groups/delete/<int:pk>/', GroupDeleteView.as_view(), name='group-delete'),
    path('intervals/', IntervalListView.as_view(), name='interval-list'),
    path('intervals/create/', IntervalCreateView.as_view(), name='interval-create'),
    path('intervals/update/<int:pk>/', IntervalUpdateView.as_view(), name='interval-update'),
    path('intervals/delete/<int:pk>/', IntervalDeleteView.as_view(), name='interval-delete'),
    
    path('file-associations/create/', FileAssociationCreateView.as_view(), name='fa-create'),
    path('file-associations/', FileAssociationListView.as_view(), name='fa-list'),
    path('file-associations/upload/<int:pk>/', CSVUploadView.as_view(), name='fa-upload'),
    path('file-associations/update/<int:pk>/', FileAssociationUpdateView.as_view(), name='fa-update'),
    path('file-associations/delete/<int:pk>/', FileAssociationDeleteView.as_view(), name='fa-delete'),
    path('global-alert/create/<int:pk>/', GlobalAlertCreateView.as_view(), name='ga-create'),
    path('global-alert/update/<int:pk>/', GlobalAlertUpdateView.as_view(), name='ga-update'),
    path('global-alert/delete/<int:pk>/', GlobalAlertDeleteView.as_view(), name='ga-delete'),
    path('global-alert/all/', GlobalAlertListView.as_view(), name='ga-all'),
    # path('target-hit/<int:pk>/', CSVTargetHitView.as_view(), name='target-hit'),
    path('csv-data/<int:pk>/', CSVListView.as_view(), name='csv-data'),
    path('filter-csv/<int:pk>/', FilterCSVView.as_view(), name='filter-csv'),
    path('csv-headers/<int:pk>/', CSVHeaderView.as_view(), name='csv-headers'),
    path('sym-int/<int:pk>/', SymIntListView.as_view(), name='sym-int'),
    path('sort-csv/<int:pk>/', SortCSVView.as_view(), name='sort-csv'),

    path('fav-row/<int:pk>/', FavoriteRowView.as_view(), name='fav-row'),
    path('fav-row/delete/<int:pk>/', DeleteFavoriteView.as_view(), name='fav-row-delete'),
    path('fav-row-list/<int:external_user_id>/', FavoriteRowListView.as_view(), name='fav-row-all'),  
 #   path('fav-row-detail/<str:row_hash>/', FavoriteRowDetailView.as_view(), name='fav-row-detail'),  
    path('sse/<int:pk>/', regular_user_views.sse_file_updates, name='sse_file_updates'),  
    path('user-alert/sse/<int:external_user_id>/', regular_user_views.sse_user_alerts, name='sse_user_alerts'),   
    path("announcement/send/", send_announcement),
    path('custom-alert/all/<int:external_user_id>/', CustomAlertView.as_view(), name='ca-all'),
    path('custom-alert/create/<int:external_user_id>/', CustomAlertCreateView.as_view(), name='ca-create'),
    path('custom-alert/update/<int:pk>/', CustomAlertUpdateView.as_view(), name='ca-update'),
    path('custom-alert/delete/<int:pk>/', CustomAlertDeleteView.as_view(), name='ca-update'),
    path('alert-logs/<int:external_user_id>/', UserTriggeredAlertsView.as_view(), name='alert-logs'),
    path("me/", UserRoleView.as_view(), name="current-user"),
    path('settings/<int:external_user_id>/', UserSettingsView.as_view(), name='settings'),
    path('settings/create/<int:pk>/', UserSettingsCreateView.as_view(), name='create-settings'),
    path('settings/update/<int:pk>/', UpdateUserSettingsView.as_view(), name='update-settings'),
]
